-- Estrutura mínima usada pelo Epidemiological Forecaster em produção.
-- As tabelas permanecem no schema public, mas não precisam ser expostas ao
-- cliente: Streamlit acessa somente a FastAPI e a API usa DATABASE_URL.

CREATE TABLE IF NOT EXISTS ef_ibge_populacao_bairro (
    ano_censo integer NOT NULL,
    bairro_norm text PRIMARY KEY,
    populacao integer NOT NULL CHECK (populacao > 0)
);

CREATE TABLE IF NOT EXISTS ef_inmet_semanal_recife (
    epi_year integer NOT NULL,
    epi_week integer NOT NULL CHECK (epi_week BETWEEN 1 AND 53),
    precipitacao_total double precision NOT NULL,
    temp_max_media double precision NOT NULL,
    time_index integer,
    week_sin double precision,
    week_cos double precision,
    atualizado_em timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (epi_year, epi_week)
);

CREATE TABLE IF NOT EXISTS ef_dengue_semanal_bairro (
    bairro_norm text NOT NULL REFERENCES ef_ibge_populacao_bairro (bairro_norm),
    epi_year integer NOT NULL,
    epi_week integer NOT NULL CHECK (epi_week BETWEEN 1 AND 53),
    time_index integer,
    casos_totais integer NOT NULL DEFAULT 0 CHECK (casos_totais >= 0),
    atualizado_em timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (bairro_norm, epi_year, epi_week)
);

CREATE INDEX IF NOT EXISTS idx_ef_dengue_semana
    ON ef_dengue_semanal_bairro (epi_year, epi_week);

CREATE TABLE IF NOT EXISTS ef_previsoes_xgboost_dashboard (
    modelo text NOT NULL,
    versao_modelo text NOT NULL,
    data_geracao timestamptz NOT NULL,
    modo_resultado text NOT NULL,
    epi_year_origem integer NOT NULL,
    epi_week_origem integer NOT NULL,
    semana_origem text NOT NULL,
    target_epi_year integer NOT NULL,
    target_epi_week integer NOT NULL,
    semana_alvo text NOT NULL,
    horizonte_semanas integer NOT NULL CHECK (horizonte_semanas BETWEEN 1 AND 4),
    bairro_norm text NOT NULL REFERENCES ef_ibge_populacao_bairro (bairro_norm),
    populacao integer NOT NULL,
    casos_observados_recentes_4s integer NOT NULL,
    incidencia_recente_4s_100k double precision NOT NULL,
    categoria_recente_observada text NOT NULL,
    categoria_prevista text NOT NULL,
    confianca_modelo double precision NOT NULL,
    prob_baixo double precision NOT NULL,
    prob_medio double precision NOT NULL,
    prob_alto double precision NOT NULL,
    prob_critico double precision NOT NULL,
    casos_observados_alvo_4s integer,
    incidencia_observada_alvo_4s_100k double precision,
    categoria_observada_alvo text,
    previsao_correta boolean,
    status_avaliacao text NOT NULL DEFAULT 'Pendente',
    data_avaliacao timestamptz,
    PRIMARY KEY (
        modo_resultado, epi_year_origem, epi_week_origem,
        horizonte_semanas, bairro_norm
    )
);

CREATE INDEX IF NOT EXISTS idx_ef_previsoes_origem
    ON ef_previsoes_xgboost_dashboard (epi_year_origem, epi_week_origem, horizonte_semanas);
CREATE INDEX IF NOT EXISTS idx_ef_previsoes_alvo
    ON ef_previsoes_xgboost_dashboard (target_epi_year, target_epi_week, status_avaliacao);

CREATE TABLE IF NOT EXISTS ef_metricas_xgboost (
    modelo text NOT NULL,
    versao_modelo text NOT NULL,
    fonte text NOT NULL,
    horizonte_semanas integer NOT NULL CHECK (horizonte_semanas BETWEEN 1 AND 4),
    n_amostras_teste integer NOT NULL,
    semanas_avaliadas integer,
    periodo_inicio text,
    periodo_fim text,
    acuracia double precision,
    acuracia_balanceada double precision NOT NULL,
    f1_macro double precision NOT NULL,
    f2_macro double precision NOT NULL,
    atualizado_em timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (fonte, versao_modelo, horizonte_semanas)
);

CREATE TABLE IF NOT EXISTS ef_pipeline_execucoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    executado_em timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL,
    semana_origem text,
    detalhes text
);

-- O navegador nunca consulta essas tabelas diretamente. Sem políticas públicas,
-- RLS bloqueia o acesso pelas chaves anon/authenticated da Data API; FastAPI e
-- GitHub Actions usam a conexão PostgreSQL mantida em segredo.
ALTER TABLE ef_ibge_populacao_bairro ENABLE ROW LEVEL SECURITY;
ALTER TABLE ef_inmet_semanal_recife ENABLE ROW LEVEL SECURITY;
ALTER TABLE ef_dengue_semanal_bairro ENABLE ROW LEVEL SECURITY;
ALTER TABLE ef_previsoes_xgboost_dashboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE ef_metricas_xgboost ENABLE ROW LEVEL SECURITY;
ALTER TABLE ef_pipeline_execucoes ENABLE ROW LEVEL SECURITY;
